apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: the925-ingress-multi
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "stickounet"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # Login API calls
          - path: /api/login
            pathType: Prefix
            backend:
              service:
                name: the925-login-service
                port:
                  number: 8080

          # Serve /login.html from login service
          - path: /login.html
            pathType: ImplementationSpecific
            backend:
              service:
                name: the925-login-service
                port:
                  number: 8080

          # Catch-all route
          - path: /
            pathType: Prefix
            backend:
              service:
                name: the925-movies-service
                port:
                  number: 8080
